# Generated by Django 2.1.2 on 2018-11-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181031_1800'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_identifier', models.IntegerField(unique=True)),
                ('internal_person_identifier', models.IntegerField()),
            ],
        ),
    ]
