# Generated by Django 2.1.2 on 2018-11-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_identifier', models.IntegerField()),
                ('home_team_external_id', models.IntegerField()),
                ('away_team_external_id', models.IntegerField()),
                ('home_team_goals', models.IntegerField()),
                ('away_team_goals', models.IntegerField()),
            ],
        ),
    ]
