# Generated by Django 2.1.2 on 2018-11-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='external_identifier',
            field=models.IntegerField(unique=True),
        ),
    ]
