# Generated by Django 2.1.2 on 2018-11-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181107_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='away_team_external_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team_goals',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_external_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team_goals',
            field=models.IntegerField(null=True),
        ),
    ]
